DATA:
  DATASET: imagenet
  IMG_SIZE: 384
  BATCH_SIZE: 512
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
MODEL:
  TYPE: vit
  NAME: vit-b_16
  NUM_CLASSES: 1000
  VIT:
    PATCH_SIZE: 16
    HIDDEN_SIZE: 768
    MLP_DIM: 3072
    NUM_HEADS: 12
    NUM_LAYERS: 12
    ATTENTION_DROP_RATE: 0.
    DROPOUT_RATE: 0.1
    CLASSIFIER: 'token'
    ZERO_HEAD: True
    PRETRAINED_WEIGHT: '/data/rentianhe/weight/vit_pytorch/ViT-B_16.npz'
TRAIN:
  MODE: step
  STEPS: 20000
  WARMUP_EPOCHS: 500
  BASE_LR: 3e-2
  WEIGHT_DECAY: 0.
  LR_SCHEDULER:
    NAME: cosine
    FREQUENCY: step
  OPTIMIZER:
    NAME: sgd
  VAL_CHECK_INTERVAL: 1000
AUG:
  MIXUP: 0.
  RANDOM_HORIZONTAL_FLIP: 0.
  SCALE: (0.05, 1.0)
  COLOR_JITTER: 0.
  AUTO_AUGMENT: none
  REPROB: 0.