DATA:
  DATASET: cifar100
  IMG_SIZE: 32
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 0
  BASE_LR: 0.1
  LR_SCHEDULER:
    NAME: step
    DECAY_RATE: 0.1
    MULTISTONES: [150, 225]
AUG:
  MIXUP: 0.
  RANDOM_HORIZONTAL_FLOP: 0.5
  RANDOM_ROTATION: 15
MODEL:
  TYPE: resnet101
  NAME: resnet101-cifar100
  NUM_CLASSES: 100
  LABEL_SMOOTHING: 0.1