DATA:
  DATASET: cifar100
  IMG_SIZE: 32
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 0.1
  WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    NAME: cosine
    DECAY_RATE: 0.1
    MULTISTONES: [150, 225]
  OPTIMIZER:
    NAME: sgd
AUG:
  MIXUP: 0.
  RANDOM_HORIZONTAL_FLOP: 0.5
  RANDOM_ROTATION: 15
MODEL:
  TYPE: resnet
  NAME: resnet50
  NUM_CLASSES: 100
  LABEL_SMOOTHING: 0.1