DATA:
  DATASET: cifar100
  IMG_SIZE: 32
MODEL:
  TYPE: densenet
  NAME: densenet161
  NUM_CLASSES: 100
  LABEL_SMOOTHING: 0.
  DENSENET:
    NUM_BLOCK: [6, 12, 36, 24]
    GROWTH_RATE: 48
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 0.1
  WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    NAME: cosine
  OPTIMIZER:
    NAME: sgd
AUG:
  MIXUP: 0.
  RANDOM_HORIZONTAL_FLOP: 0.5
  RANDOM_ROTATION: 15