input:
    size: (32, 32)

model:
    name: 'resnet18'
    classes: 100

dataset:
    name: 'cifar100'
    dir: './data/cifar100'
    batch_size: 128
    eval_batch_size: 64

dataloader:
    num_workers: 8
    pin_memory: True
    drop_last: True

transforms:
    tensor:
        normalization:
            mean: [0.5070751592371323, 0.48654887331495095, 0.4409178433670343]
            std: [0.2673342858792401, 0.2564384629170883, 0.27615047132568404]
    img:
        train:
            Resize:
                enable: 1
                size: (32, 32)
            RandomCrop:
                enable: 1
                size: 32
                padding: 4
            RandomHorizontalFlip:
                enable: 0
                p: 0.5
            RandomVerticalFlip:
                enable: 0
                p: 0.5
            RandomRotation:
                enable: 0
                degrees: 15
        test:
            Resize:
                enable: 1
                size: (32, 32)

training:
    warmup_epoch: 1
    epoch: 200
    save_epoch: 15
    eval_every_epoch: True
    label_smoothing:
        enable: 0
        smoothing: 0.1
    no_bias_decay:
        enable: 0
    mixed_precision_training:
        enable: 0
    distributed_training:
        enable: 0
        world_size: 4

optim:
    name: 'SGD'
    lr: 0.1
    momentum: 0.9
    weight_decay: 5e-4

scheduler:
    name: 'MultiStepLR'
    milestones: [60, 120, 160]
    gamma: 0.2

save_dir:
    ckpts_dir: 'ckpts'

